services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf:/etc/nginx/conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - php74
    networks:
      - app_network

  mysql:
    image: mysql:5.7
    container_name: mysql57
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: nopassword
      MYSQL_DATABASE: dbname
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config/my.cnf:/etc/my.cnf
    networks:
      - app_network 

  php74:
    build:
      context: .
      dockerfile: php/dockerfile-74      
    container_name: php74
    volumes:
      - ./web:/var/www/html
      - ./php/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - app_network

  php81:
    build:
      context: .
      dockerfile: php/dockerfile-81
    container_name: php81
    volumes:
      - ./web:/var/www/html
      - ./php/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - app_network
  
  redis:
    image: redis:7.4.1
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network      
networks:
  app_network:
    driver: bridge