# Use a Node.js base image
FROM node:18

# Copy project folder into the container
COPY ./web/your_project /app/your_project

# Set the working directory
WORKDIR /app/your_project

# Install PM2 globally
RUN npm install -g pm2

# Install depends
RUN echo y | npm install --silent
RUN echo y | npx prisma generate
RUN npm run build

# Expose the desired port
EXPOSE 3001

# Start the app using PM2 in cluster mode
CMD ["pm2-runtime", "start", "/app/your_project/ecosystem.config.cjs"]